---
title: "VTrack_GSB"
author: "Ryan Freedman"
date: "2/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library of Goodies
```{r}
#Add Packages
library(tidyverse)
library(sf)
library(sp)
library(ggpubr)
library(readxl)
library(lubridate)
library(raster)
library(rworldmap)
library(ggplot2)
library(scales) 
library(here)
library(ggrepel)
library(tidyselect)
library(dplyr)
library(ADePTR)
library(raster)
library(gganimate)
library(VTrack)
library(forecast)
```


Data here are being added fresh. Vtrack can take data right from VEMCO
```{r}

gsb.raw<-read.csv('GSB_detections_25Oct2019_Clean.csv') #vemco spit out
gsb.raw$Transmitter.Serial<-str_sub(gsb.raw$Transmitter, -4)
colnames(gsb.raw)<-c("Date.Time", "Receiver", "Transmitter","Transmitter.Name", "Transmitter.Serial", "Sensor.Value", "Sensor.Unit", "Station.Name", "Latitude", "Longitude")
gsb.raw$Date.Time<-as.POSIXct(gsb.raw$Date.Time, tz="America/Los_Angeles", format= "%m/%d/%y %H:%M")

gsb.site<-read.csv('GSBsites.csv') %>% #created in excel
  subset(select=c(Site, Lat_dd, Lon_dd))

colnames(gsb.site)<-c("LOCATION", "LATITUDE", "LONGITUDE")
gsb.site$RADIUS<-250 #addition of radius 
  

```

Convert the files in the Vtrack required base formula
```{r}

Vbass<- ReadInputData(infile=gsb.raw,iHoursToAdd=10, dateformat = NULL) 

CircuitousDM <- GenerateCircuitousDistance(gsb.site)

```

